spring:
    application:
      name: elk-spike

#    jpa:
#      hibernate.ddl-auto: update

    datasource:
      url: jdbc:mysql://${MYSQL_HOST}:3306/elk_spike
      username: root
      password: admin
      driver-class-name: com.mysql.jdbc.Driver
#spring.jpa.show-sql: true

#logging:
#  file:
#    name: C:/Users/y.yalung/Desktop/logback/spring-boot-logging.log
